### ISSUE TITLE
raise KeyError("Hub does not exist or is inaccessible.")

### ISSUE THREAD

**Issue by joelhempenius** [Esri/hub-py#110]
I get this error when cloning a site from Enterprise 10.8.1 to ArcGIS Hub Premium.
(self._gis.properties['portalProperties']['sharedTheme']) is not available in the object. 
What should i do to fix this?

**Comment by andybell** [comment]
Also experiencing this issue in ArcGIS Online when trying to clone a hub site. Work around solution is to make sure that the organization has "Shared theme colors" explicitly set (Organization -> Settings -> General -> Shared Theme -> Manage shared theme colors). 
![image (2)](https://user-images.githubusercontent.com/7776675/150197019-31adf458-ae67-43ed-8f13-68c48651d833.png)
