### ISSUE TITLE
Hot spot analysis example for hub.py redesign

### ISSUE THREAD

**Issue by ManushiM** [Esri/hub-py#32]
```
from arcgis.hub import * 

#User-defined inputs
url = ''
username = ''
password = ''
initiative_id = ''

#Connect to Hub
gis = GIS(url, username, password)
myHub = gis.hub

#Fetch VZ initiative
initiative = myHub.initiatives.get(initiative_id)

#Fetch crash indicator
crash = initiative.indicators.get('crash')
crash_url = crash.url

#Perform analysis
hotspot_crash = arcgis.analysis.hotspot(with parameters)

#Publish to AGOL if doesn't exist, else update
if does not exist:
    published = gis.content.import_data(hotspot_crash)
else:
    #fetch item, update

#Add 'hotspot_crash' indicator to VZ initiative
indicator_properties = {...}
initiative.indicators.add(indicator_properties)

```

**Comment by ajturner** [comment]
- `initiative.indicators.search()` should accept query parameters, which can void the subsequent filtering logic, or there should be a similar `#get()`
  - e.g. `crash = initiative.indicators.search(id='crash')`
  - or `crash = initiative.indicators.get('crash')`
- the last line should be plural? `initiative.indicators.add(indicator_properties)`
- what occurs if there is a duplicate indicator ID? Does the method fail or auto-update?

**Comment by ManushiM** [comment]
* right, updated it to `indicators.get()`
* Updated the last line
* I haven't tested duplicate indicators yet. Let me test and account for that.
