### ISSUE TITLE
Support for export all Hub community members

### ISSUE THREAD

**Issue by ajturner** [Esri/hub-py#33]
This is a bit complicated due to restrictions of the AGO api for protecting user credentials. Here is a rough sketch.

- Given an Initiative, get the full list of followers
  - include username, joined date, email (only if Community Admin)

This call should work for 
- Anonymous - only get for public initiatives and public users (per API)
- Core Member - ability to get all members (will not include email)
- Core Member with Community Admin credentials - (includes Email)

For this to work for both non-Community Admin and with Community Admin the Hub will need to support the option to also add Credentials for the community org. This may look something

```python
hub = GIS.hub("https://opendata.dc.gov")
dcInitiatives = hub.initiatives.search()
initiativeFollowers = dcInitiatives[0].followers
firstUser = initiativeFollowers[0] 
firstUser.username #=> 'sally'
firstUser.email #=> Null

# Hub has reference to 2 Orgs: Enterprise + Community. First, they are both 'anonymous'
hub._enterpriseGIS 
hub._communityGIS

# Sign into the Enterprise Org. This will replace/store hub._enterpriseGIS with a signed in GIS
hub.enterpriseSignin(enterpriseUsername, enterprisePassword) #=> True (success)

# Sign into the Community Org. This will replace/store hub._communityGIS with a signed in GIS
hub.communitySignin(communityUsername, communityPassword) #=> True

# Now the requests return additional information
dcInitiatives = hub.initiatives.search()
initiativeFollowers = dcInitiatives[0].followers
firstUser = initiativeFollowers[0] 

# getting profile information may require 'lazy loading' during each user (group.users doesn't return this info)
firstUser.username #=> 'sally'
firstUser.email #=> `sally@example.com`
```

## Add Support for Referencing both Orgs

As we've discussed, I think that we need to add caching of both organizations (enterprise + community) so that the right org can be used explicitly in other methods.  

in [Hub.__init__](https://github.com/esridc/hub-py/blob/66b1c4ba539cbf17387a7f7b6825a0fd62b5f5c3/arcgishub/hub.py#L41-L49) - add something like the following (but with much better error checking)

```python
    def __init__(self, gis, username=None, password=None):
        self.gis = gis
        self._username = username
        self._password = password
        self.gis = GIS(self.url, self._username, self._password)
        try:
            self._gis_id = self.gis.properties.id
            # add test if actually a Hub
            # orgType is either 'enterprise' or 'community'
            self._hubRole = self.gis.properties.portalProperties.hub.settings.orgType 
            if self._hubRole == 'enterprise':
                self._enterpriseGIS = self.gis
                self._communityGIS = GIS(self.community_org_url)
            elif self._hubRole == 'community':
                self._enterpriseGIS = GIS(self.enterprise_org_url)
                self._communityGIS = self.gis
        except AttributeError:
            self._gis_id = None

    def enterpriseSignin(username=None, password=None)
        self._enterpriseGIS = GIS(self.enterprise_org_url, username, password)

    def communitySignin(username=None, password=None)
        self._communityGIS = GIS(self.community_org_url, username, password)

```

@ManushiM

**Comment by ManushiM** [comment]
I am slightly fuzzy with understanding how the community bit works. Could you please clarify it, so that I can prioritize it in backlog accordingly?

**Comment by ajturner** [comment]
@ManushiM I added more details in the description.

**Comment by ManushiM** [comment]
@ajturner You have to be signed it to get followers for public initiatives as well. Both in UI and the Python API.

**Comment by ManushiM** [comment]
@ajturner also, I am not sure if having `enterpriseSignIn` and `communitySignIn` is a good idea.

Per https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/ there are several ways of signing in to the `GIS` and restricting it for the companion org might not seem like a consistent login pattern for users.

I have another suggestion for this:
```
egis = GIS(e_org_url, username, password)
eHub = egis.hub

i = eHub.initiatives.get('4ef..')

cgis = GIS(c_org_url, username, password)

i.get_followers(cgis)
```

It matches the UX on the website too. As an eOrg admin, you are required to sign in as cOrg admin to see all the followers of the initiative, without losing control as eOrg admin.

**Comment by ajturner** [comment]
Those are good points. So make Community GIS optional. If included it provides additional metadata.

`i.followers(community=Null, filter=Null)`
