### ISSUE TITLE
Does not support verify_cert parameter

### ISSUE THREAD

**Issue by eanderson2030** [Esri/hub-py#95]
Hello,

I am attempting to make a connection to our Portal using the following code:

from arcgishub.hub import Hub
dev = Hub("PORTALURL","USERNAME","PASSWORD")

When I do, I get the following error: 

_SSLError: Please set verify_cert=False due to encountered SSL error: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: /gii/sharing/rest/info?f=json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))_

If I try to add "verify_cert=False" to the connection, like so:

dev = Hub("PORTALURL","USERNAME","PASSWORD",verify_cert=False)

I now get the error:

TypeError: __init__() got an unexpected keyword argument 'verify_cert'

---------------------------------------------------------------------

Is verify_cert not supported when making a connection attempt here?

Thank you,
Eric

**Comment by steflef** [comment]
Same here.

**Comment by steflef** [comment]
Quick fix via hub.py
Will Pull request if the fix seems OK.

class Hub(object):
    """
    Entry point into the Hub module. Lets you access an individual hub and its components.
       
    ================    ===============================================================
    **Argument**        **Description**
    ----------------    ---------------------------------------------------------------
    url                 Required string. If no URL is provided by user while connecting 
                        to the GIS, then the URL will be ArcGIS Online.
    ----------------    ---------------------------------------------------------------
    username            Optional string as entered while connecting to GIS. The login user name 
                        (case-sensitive).
    ----------------    ---------------------------------------------------------------
    password            Optional string as entered while connecting to GIS. If a username is 
                        provided, a password is expected.  This is case-sensitive. If the password 
                        is not provided, the user is prompted in the interactive dialog.
    ----------------    ---------------------------------------------------------------
    verify_cert         Optional boolean. If a site has an invalid SSL certificate or is being 
                        accessed via the IP or hostname instead of the name on the certificate, 
                        set this value to False. This will ensure that all SSL certificate issues 
                        are ignored. The default is True. Warning Setting the value to False can 
                        be a security risk.
    ================    ===============================================================
    """
    
    def __init__(self, url, username=None, password=None, verify_cert=True):
        #self.gis = gis
        self._username = username
        self._password = password
        self.url = url
        self.ssl = verify_cert
        self.gis = GIS(self.url, self._username, self._password, verify_cert=self.ssl)
        try:
            self._gis_id = self.gis.properties.id
        except AttributeError:
            self._gis_id = None

**Comment by eanderson2030** [comment]
Hi @steflef ,

After making the change you suggested to the hub.py file, I seem to still be getting the following error:

TypeError: __init__() got an unexpected keyword argument 'verify_cert'

Thank you for your help!

-Eric

**Comment by steflef** [comment]
I'm using Jupyter, so:

Step 1:  finding the right package (location param): pip show arcgishub
Step 2:  apply the quick fix to hub.py
Step 3: restart Jupyter Kernel

Next, test:
# SSO Window's
from arcgishub.hub import Hub
hub_06 = Hub("https://your_server/portal", verify_cert=False)

# Admin+ password
from arcgishub.hub import Hub
hub_03 = Hub("https://your_server/portal", "your_user", verify_cert=False) 
#will prompt for password

**Comment by eanderson2030** [comment]
Thank you @steflef for the suggestion to check 'pip show arcgishub'. I was making the change to the wrong hub.py file located in **...\envs\arcgispro-py3-clone\Lib\site-packages\arcgis\apps\hub** instead of **...\envs\arcgispro-py3-clone\src\arcgishub\arcgishub**.

After making this change, I am now able to successfully connect to our Portal using the verify_cert=False parameter, however, I am now getting an error AttributeError: 'Hub' object has no attribute 'sites'. I was not getting this before even when testing with an ArcGIS Online Hub site.

Did you have any thoughts on that? And thank you again for your help.

**Comment by eanderson2030** [comment]
My simple code is as follows:

`from arcgishub.hub import Hub

devHub = Hub("https://portal/webadaptor","adminusername","adminpassword",verify_cert=False)

preprod = Hub("https://portal/webadaptor","adminusername","adminpassword",verify_cert=False)

item = devHub.sites.get('item ID of site')`

Output: AttributeError: 'Hub' object has no attribute 'sites'

**Comment by eanderson2030** [comment]
Hi @steflef , doing a fresh re-install of the arcgis hub module and then making sure to apply the fix you noted to the ...\envs\arcgispro-py3-clone\Lib\site-packages\arcgis\apps\hub\hub.py file resolved the verify_cert issue and I was able to connect to our sites as well.

Thanks again for your help!

-Eric

**Comment by steflef** [comment]
Hi @eanderson2030,
Great and thanks for your follow-up.
Cheers!

-Stef

**Comment by ManushiM** [comment]
Fixed in v2.0.5
